import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import { useSession, signIn, signOut } from "next-auth/react";
import Link from "next/link";
import { useTheme } from "next-themes";
import Navbar from "@/components/Navbar";

const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />

        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="container mx-auto flex flex-col items-center justify-center p-4">
        <button onClick={() => signIn()}>SignIn</button>
      </main>
    </>
  );
};

export default Home;
